# version: '3'
# services:
#   node:
#     image: "node:alpine"
#     build: './server'
#     ports: 
#       - "3333:3333"
#     volumes:
#       - "./server:/server"
#     working_dir: /server
#     command: npm start
      

    