version: '3'
services:
  front-end:
    build: './app'
    ports:
      - '8080:80'
    restart: always
  back-end:
    build: './server'
    ports:
      - 3333:3333
    command: "npm start"
  #  volumes:
  #     - ./server:/server
  #   working_dir: /server
    